import './style.css';
import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';

type Params={mass:number;radius:number;speed:number;showVectors:boolean;showTrail:boolean;running:boolean};
const defaults:Params={mass:.5,radius:2,speed:4,showVectors:true,showTrail:true,running:true};
let params={...defaults},theta=0,last=performance.now(),uiTick=0;
const app=document.querySelector<HTMLDivElement>('#app')!;const fmt=(n:number,d=2)=>n.toFixed(d).replace('.',',');
function template(){return `<div class="shell"><header><div class="brand"><span class="mark">↻</span><div><b>Physics Lab</b><small>Praktikum Virtual · Gerak Melingkar 3D</small></div></div><button id="resetTop" class="ghost">Reset</button><button id="themeToggle" class="theme-toggle" type="button">Mode Gelap</button></header><main class="layout"><aside class="panel analysis"><div class="eyebrow">ANALISIS LANGSUNG</div><div class="stats"><div><span>Gaya sentripetal</span><b id="force">0</b><small>N</small></div><div><span>Periode</span><b id="period">0</b><small>s</small></div><div><span>Kecepatan sudut</span><b id="omega">0</b><small>rad/s</small></div><div><span>Frekuensi</span><b id="freq">0</b><small>Hz</small></div><div class="wide"><span>Percepatan sentripetal</span><b id="accel">0</b><small>m/s²</small></div></div><div class="formula"><b>Fₛ = mv²/r</b><span>Gaya menuju pusat lintasan</span><b>aₛ = v²/r</b><span>Percepatan radial</span></div><div class="chartbox"><div class="charttitle">Fₛ terhadap v²</div><canvas id="chart" width="520" height="160"></canvas></div></aside><aside class="panel controls"><div class="eyebrow">VARIABEL</div><div class="actions"><button id="pause" class="secondary">Jeda</button><button id="apply" class="primary">Terapkan</button></div><label>Massa <output id="massOut">0,50 kg</output><input data-key="mass" type="range" min=".1" max="2" step=".05" value=".5"></label><label>Jari-jari <output id="radiusOut">2,00 m</output><input data-key="radius" type="range" min=".5" max="4" step=".1" value="2"></label><label>Kecepatan <output id="speedOut">4,00 m/s</output><input data-key="speed" type="range" min="1" max="8" step=".1" value="4"></label><div class="toggles"><label><span>Vektor</span><input data-toggle="vectors" type="checkbox" checked></label><label><span>Jejak</span><input data-toggle="trail" type="checkbox" checked></label></div><div class="question"><b>Eksperimen</b><p>Gandakan v. Bagaimana perubahan Fₛ?</p></div></aside><section class="panel stage"><div class="stagebar"><span class="tag">3D VIEWPORT · 16:9 · WEBGL</span><span id="stageState">BERJALAN</span></div><div id="viewport" class="viewport"><div class="hud"><span>Fₛ menuju pusat</span><span id="hudValues">v = 4,00 m/s</span></div></div><div class="legend"><span><i class="ball"></i>Benda</span><span><i class="force"></i>Gaya sentripetal</span><span><i class="velocity"></i>Kecepatan</span></div></section></main><footer><span>PHYSICS LAB / SUKA OLIMPIADE FISIKA</span><span>Three.js · Model 3D</span></footer></div>`}
function main(){app.innerHTML=template();const viewport=document.querySelector<HTMLElement>('#viewport')!;const scene=new THREE.Scene();scene.background=new THREE.Color(0x101b17);const camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.set(5.8,5.7,7.5);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;viewport.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,0,0);controls.maxPolarAngle=Math.PI*.48;controls.minDistance=5;controls.maxDistance=14;
scene.add(new THREE.HemisphereLight(0xeafff4,0x26382d,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(4,7,5);light.castShadow=true;scene.add(light);const ground=new THREE.Mesh(new THREE.CircleGeometry(4.7,64),new THREE.MeshStandardMaterial({color:0x17261f,roughness:.9,metalness:.1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.08;ground.receiveShadow=true;scene.add(ground);
const group=new THREE.Group();scene.add(group);const ring=new THREE.LineLoop(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0x65d8e3,transparent:true,opacity:.75}));group.add(ring);const axis=new THREE.AxesHelper(4.7);axis.position.y=.01;axis.material.transparent=true;axis.material.opacity=.22;group.add(axis);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.22,.22,.18,32),new THREE.MeshStandardMaterial({color:0xbdd44a,emissive:0x263a10,emissiveIntensity:1}));hub.position.y=.08;hub.castShadow=true;scene.add(hub);const ball=new THREE.Mesh(new THREE.SphereGeometry(.25,24,16),new THREE.MeshStandardMaterial({color:0x65d8e3,emissive:0x12383b,emissiveIntensity:1,roughness:.3,metalness:.2}));ball.castShadow=true;scene.add(ball);
const trail=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0x65d8e3,transparent:true,opacity:.35}));scene.add(trail);const forceArrow=new THREE.ArrowHelper(new THREE.Vector3(-1,0,0),new THREE.Vector3(),1,0xbdd44a,.18,.1);const velArrow=new THREE.ArrowHelper(new THREE.Vector3(0,0,1),new THREE.Vector3(),1,0xf39b68,.18,.1);scene.add(forceArrow,velArrow);
function resize(){const r=viewport.getBoundingClientRect();camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false)}resize();new ResizeObserver(resize).observe(viewport);
function refreshGeometry(){const pts=[];for(let i=0;i<128;i++){const a=i/128*Math.PI*2;pts.push(new THREE.Vector3(params.radius*Math.cos(a),.07,params.radius*Math.sin(a)))}ring.geometry.dispose();ring.geometry=new THREE.BufferGeometry().setFromPoints(pts);}
function updateScene(){const p=new THREE.Vector3(params.radius*Math.cos(theta),.25,params.radius*Math.sin(theta));ball.position.copy(p);const radial=new THREE.Vector3(-Math.cos(theta),0,-Math.sin(theta));const tangent=new THREE.Vector3(-Math.sin(theta),0,Math.cos(theta));const arrowLength=Math.min(1.25,Math.max(.5,params.speed/5));forceArrow.visible=velArrow.visible=params.showVectors;forceArrow.position.copy(p);forceArrow.setDirection(radial);forceArrow.setLength(arrowLength);velArrow.position.copy(p);velArrow.setDirection(tangent);velArrow.setLength(arrowLength*.9);if(params.showTrail){const pts=[];for(let i=0;i<80;i++){const a=theta-i*.055;pts.push(new THREE.Vector3(params.radius*Math.cos(a),.25,params.radius*Math.sin(a)))}trail.geometry.dispose();trail.geometry=new THREE.BufferGeometry().setFromPoints(pts);trail.visible=true}else trail.visible=false;}
function drawChart(){const chart=document.querySelector<HTMLCanvasElement>('#chart')!,c=chart.getContext('2d')!,w=chart.width,h=chart.height;c.clearRect(0,0,w,h);c.fillStyle='#131c17';c.fillRect(0,0,w,h);c.strokeStyle='#405246';c.beginPath();c.moveTo(42,10);c.lineTo(42,h-25);c.lineTo(w-8,h-25);c.stroke();c.fillStyle='#94a89a';c.font='10px monospace';c.fillText('Fₛ',8,16);c.fillText('v²',w-25,h-8);const maxV=64,maxF=Math.max(1,params.mass*maxV/params.radius);c.strokeStyle='#65d8e3';c.lineWidth=2;c.beginPath();for(let i=0;i<=40;i++){const v2=maxV*i/40,x=42+(w-50)*i/40,y=h-25-(h-38)*(params.mass*v2/params.radius)/maxF;i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();const x=42+(w-50)*params.speed**2/maxV,y=h-25-(h-38)*(params.mass*params.speed**2/params.radius)/maxF;c.fillStyle='#bdd44a';c.beginPath();c.arc(x,y,4,0,Math.PI*2);c.fill();}
function ui(){const force=params.mass*params.speed**2/params.radius,accel=params.speed**2/params.radius,period=2*Math.PI*params.radius/params.speed;document.querySelector('#force')!.textContent=fmt(force);document.querySelector('#accel')!.textContent=fmt(accel);document.querySelector('#period')!.textContent=fmt(period);document.querySelector('#omega')!.textContent=fmt(params.speed/params.radius);document.querySelector('#freq')!.textContent=fmt(1/period);document.querySelector('#hudValues')!.textContent=`v = ${fmt(params.speed)} m/s · Fₛ = ${fmt(force)} N`;drawChart()}
refreshGeometry();ui();function loop(now:number){const dt=Math.min(.05,(now-last)/1000);last=now;if(params.running)theta+=params.speed/params.radius*dt;updateScene();controls.update();renderer.render(scene,camera);if(++uiTick%5===0)ui();requestAnimationFrame(loop)}requestAnimationFrame(loop);
const out:any={mass:'massOut',radius:'radiusOut',speed:'speedOut'};document.querySelectorAll<HTMLInputElement>('[data-key]').forEach(i=>i.addEventListener('input',()=>{const k=i.dataset.key as keyof Pick<Params,'mass'|'radius'|'speed'>;params[k]=Number(i.value);document.querySelector('#'+out[k])!.textContent=fmt(params[k])+(k==='mass'?' kg':k==='radius'?' m':' m/s');refreshGeometry();ui()}));document.querySelectorAll<HTMLInputElement>('[data-toggle]').forEach(i=>i.addEventListener('change',()=>{if(i.dataset.toggle==='vectors')params.showVectors=i.checked;if(i.dataset.toggle==='trail')params.showTrail=i.checked}));document.querySelector('#pause')!.addEventListener('click',e=>{params.running=!params.running;(e.currentTarget as HTMLButtonElement).textContent=params.running?'Jeda':'Lanjutkan';document.querySelector('#stageState')!.textContent=params.running?'BERJALAN':'DIJEDA'});document.querySelector('#apply')!.addEventListener('click',()=>{theta=0;params.running=true;document.querySelector('#pause')!.textContent='Jeda';document.querySelector('#stageState')!.textContent='BERJALAN';ui()});document.querySelector('#resetTop')!.addEventListener('click',()=>location.reload())}
main();

const themeToggle=document.querySelector<HTMLButtonElement>('#themeToggle'); const savedTheme=localStorage.getItem('simulasi-theme')||'light'; document.documentElement.dataset.theme=savedTheme; if(themeToggle){themeToggle.textContent=savedTheme==='dark'?'Mode Terang':'Mode Gelap'; themeToggle.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('simulasi-theme',next);themeToggle.textContent=next==='dark'?'Mode Terang':'Mode Gelap';});}
