import './style.css';
import {state} from './physics';
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;
let mass=.5,k=100,amplitude=.03,mode='static',running=false,time=0,last=performance.now();
const f=(v:number,d=2)=>v.toLocaleString('id-ID',{minimumFractionDigits:d,maximumFractionDigits:d});
$('#app').innerHTML=`<div class="shell"><header><div class="brand"><span class="mark">∿</span><div><b>Physics Lab</b><small>Praktikum virtual · Pegas</small></div></div><button id="resetTop" class="ghost">Reset</button></header><main class="hooke-layout"><div class="sidebar"><aside class="panel controls"><div class="actions"><button id="apply" class="primary">Terapkan</button><button id="pause" class="secondary">Jeda</button></div><div class="modes"><button data-mode="static" class="active">Keseimbangan</button><button data-mode="oscillation">Osilasi</button></div><label>Massa beban <output id="massOut"></output><input id="mass" type="range" min=".1" max="2" step=".05" value=".5"></label><label>Konstanta pegas <output id="kOut"></output><input id="stiffness" type="range" min="50" max="250" step="5" value="100"></label><label id="amplitudeLabel">Tarikan dari posisi seimbang <output id="ampOut"></output><input id="amplitude" type="range" min="0" max="4.905" step=".1" value="3"></label><div class="toggles"><label><span>Arah gaya</span><input id="vectors" type="checkbox" checked></label><label><span>Posisi seimbang</span><input id="guide" type="checkbox" checked></label></div><p class="intro">Ubah massa untuk membandingkan pertambahan panjang. Pada mode osilasi, tarik beban lalu tekan Lepaskan. g = 9,81 m/s².</p></aside><aside class="panel analysis"><div class="eyebrow">ANALISIS LANGSUNG</div><div class="stats"><div><span>Pertambahan panjang</span><b id="extension"></b><small>cm</small></div><div><span>Gaya pegas</span><b id="force"></b><small>N</small></div><div><span>Panjang seimbang Δx</span><b id="equilibrium"></b><small>cm</small></div><div><span>Periode ideal</span><b id="period"></b><small>s</small></div></div><div class="energy"><span>Energi osilasi</span><div><i id="pe"></i><i id="ke"></i></div><small id="energyText"></small></div><p class="intro">Energi potensial efektif diukur dari posisi seimbang (pegas + gravitasi). Osilasi ideal tanpa redaman.</p></aside></div><section class="panel stage"><div class="stagebar"><span class="tag">PENGAMATAN · 16:9</span><span id="status">SEIMBANG</span></div><div class="viewport"><canvas id="scene" aria-label="Pegas vertikal dengan beban, penggaris sentimeter, dan vektor gaya"></canvas></div><div class="legend"><span><i class="force"></i>Gaya pegas</span><span><i class="velocity"></i>Berat beban</span><span>Garis putus: posisi seimbang</span></div><div class="plot-section"><div class="plot-heading"><label>Grafik pengamatan <select id="chartType"><option value="hooke">Gaya terhadap pertambahan panjang</option><option value="time">Simpangan terhadap waktu</option></select></label><span id="chartNote"></span></div><canvas id="chart" aria-label="Grafik hubungan gaya dan pertambahan panjang"></canvas></div></section></main><footer><span>SUKA OLIMPIADE FISIKA</span><span>Canvas · Model pegas ideal</span></footer></div>`;
const canvas=$<HTMLCanvasElement>('#scene'),ctx=canvas.getContext('2d')!,chart=$<HTMLCanvasElement>('#chart'),cc=chart.getContext('2d')!;
function size(c:HTMLCanvasElement){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);c.getContext('2d')!.setTransform(d,0,0,d,0,0);return {w:r.width,h:r.height};}
function arrow(x:number,y:number,end:number,color:string,label:string){ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,end);ctx.stroke();const sign=Math.sign(end-y);ctx.beginPath();ctx.moveTo(x,end);ctx.lineTo(x-6,end-sign*10);ctx.lineTo(x+6,end-sign*10);ctx.closePath();ctx.fill();ctx.font='12px Arial';ctx.fillText(label,x+10,(y+end)/2);}
function draw(){const s=state(mass,k,amplitude,time,mode==='oscillation'),w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#101b17';ctx.fillRect(0,0,w,h);
const top=h*.12,scale=h*.78/.8,cx=w*.44,natural=.2,bottom=top+(natural+s.extension)*scale,equilibrium=top+(natural+s.equilibrium)*scale,blockW=Math.max(30,Math.min(62,w*.09)),blockH=h*.105;
ctx.fillStyle='#85968b';ctx.fillRect(cx-65,top-12,130,10);ctx.fillStyle='#35483d';ctx.fillRect(cx-70,top-24,140,12);
const rx=w*.76;ctx.fillStyle='#1c2e23';ctx.fillRect(rx-7,top-5,52,.8*scale+12);ctx.font='11px monospace';ctx.textBaseline='middle';for(let cm=0;cm<=80;cm+=2){const y=top+cm/100*scale;ctx.strokeStyle='#92a59a';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(rx,y);ctx.lineTo(rx+(cm%10===0?14:7),y);ctx.stroke();if(cm%10===0){ctx.fillStyle='#bdcbbc';ctx.fillText(String(cm),rx+19,y);}}ctx.fillStyle='#bdcbbc';ctx.fillText('cm',rx+12,top-16);
ctx.setLineDash([5,5]);ctx.strokeStyle='#6c7e71';ctx.beginPath();ctx.moveTo(cx-80,top+natural*scale);ctx.lineTo(rx,top+natural*scale);ctx.stroke();if($<HTMLInputElement>('#guide').checked){ctx.strokeStyle='#bdd44a';ctx.beginPath();ctx.moveTo(cx-80,equilibrium);ctx.lineTo(rx,equilibrium);ctx.stroke();}ctx.setLineDash([]);
ctx.strokeStyle='#c6d2cf';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(cx,top);ctx.lineTo(cx,top+8);for(let i=0;i<=180;i++){const t=i/180,y=top+8+t*(bottom-top-16),x=cx+Math.sin(t*Math.PI*24)*w*.018;ctx.lineTo(x,y);}ctx.lineTo(cx,bottom);ctx.stroke();
ctx.fillStyle='#56736d';ctx.fillRect(cx-blockW/2,bottom,blockW,blockH);ctx.fillStyle='#89b8a5';ctx.fillRect(cx-blockW/2,bottom,blockW,5);ctx.fillStyle='#eff5ef';ctx.font='12px monospace';ctx.textAlign='center';ctx.fillText(`${f(mass)} kg`,cx,bottom+blockH*.55);ctx.textAlign='left';
ctx.fillStyle='#92a59a';ctx.font='12px Arial';ctx.fillText('L₀ = 20 cm',w*.04,top+natural*scale-12);ctx.fillStyle='#bdd44a';ctx.fillText(`Δx = ${f(s.extension*100)} cm`,w*.04,h*.9);if($<HTMLInputElement>('#vectors').checked){const base=bottom+blockH/2,len=Math.min(h*.16,14+s.weight*2);arrow(cx-blockW/2-20,base,base-len*s.springForce/s.weight,'#bdd44a','Fₛ');arrow(cx+blockW/2+20,base,base+len,'#f39b68','mg');}}
function line(x1:number,y1:number,x2:number,y2:number){cc.beginPath();cc.moveTo(x1,y1);cc.lineTo(x2,y2);cc.stroke();}
function plot(){const w=chart.clientWidth,h=chart.clientHeight,left=53,right=w-20,top=28,bottom=h-35,modeTime=$<HTMLSelectElement>('#chartType').value==='time';cc.clearRect(0,0,w,h);cc.fillStyle='#121e18';cc.fillRect(0,0,w,h);cc.font='11px Arial';cc.textBaseline='middle';const xmax=modeTime?5:.4,ymax=modeTime?Math.max(.01,amplitude):100;const px=(x:number)=>left+(right-left)*x/xmax,py=(y:number)=>modeTime?top+(bottom-top)*(.5-y/(2*ymax)):bottom-(bottom-top)*y/ymax;
cc.strokeStyle='#283c30';cc.fillStyle='#92a59a';for(let i=0;i<=4;i++){const x=xmax*i/4;line(px(x),top,px(x),bottom);cc.fillText(f(modeTime?x:x*100,modeTime?1:0),px(x)-8,bottom+15);const y=modeTime?ymax*(1-i/2):ymax*i/4;line(left,py(y),right,py(y));cc.fillText(f(modeTime?y*100:y,modeTime?1:0),5,py(y));}cc.fillText(modeTime?'Simpangan (cm)':'Gaya (N)',left,12);cc.fillText(modeTime?'t (s)':'Δx (cm)',right-45,h-8);cc.strokeStyle='#65d8e3';cc.lineWidth=2;cc.beginPath();for(let i=0;i<=200;i++){const x=xmax*i/200,y=modeTime?amplitude*Math.cos(Math.sqrt(k/mass)*x):k*x;i?cc.lineTo(px(x),py(y)):cc.moveTo(px(x),py(y));}cc.stroke();const s=state(mass,k,amplitude,time,mode==='oscillation');const x=modeTime?time%5:s.extension,y=modeTime?s.displacement:s.springForce;if(x<=xmax){cc.fillStyle='#bdd44a';cc.beginPath();cc.arc(px(x),py(y),5,0,Math.PI*2);cc.fill();}$('#chartNote').textContent=modeTime?'Simpangan dari posisi seimbang':'Kemiringan garis = k';}
function ui(){const s=state(mass,k,amplitude,time,mode==='oscillation');$('#extension').textContent=f(s.extension*100);$('#force').textContent=f(s.springForce);$('#equilibrium').textContent=f(s.equilibrium*100);$('#period').textContent=f(s.period);$('#massOut').textContent=f(mass)+' kg';$('#kOut').textContent=f(k,0)+' N/m';$('#ampOut').textContent=f(amplitude*100)+' cm';$('#amplitudeLabel').hidden=mode==='static';$('#apply').textContent=mode==='static'?'Terapkan':'Lepaskan';$<HTMLButtonElement>('#pause').disabled=mode==='static';$('#pause').textContent=running?'Jeda':'Lanjutkan';$('#status').textContent=mode==='static'?'SEIMBANG':running?'BEROSILASI':'DITAHAN / DIJEDA';$('#pe').style.width=(s.energy?s.potential/s.energy*100:0)+'%';$('#ke').style.width=(s.energy?s.kinetic/s.energy*100:0)+'%';$('#energyText').textContent=`Eₚ = ${f(s.potential,3)} J · Eₖ = ${f(s.kinetic,3)} J · Total = ${f(s.energy,3)} J`;plot();}
function resize(){size(canvas);size(chart);draw();ui();}new ResizeObserver(resize).observe($('.stage'));resize();
for(const id of ['mass','stiffness','amplitude'])$<HTMLInputElement>('#'+id).addEventListener('input',()=>{mass=Number($<HTMLInputElement>('#mass').value);k=Number($<HTMLInputElement>('#stiffness').value);const a=$<HTMLInputElement>('#amplitude');a.max=String(Math.min(10,mass*9.81/k*100));amplitude=Math.min(Number(a.value)/100,mass*9.81/k);a.value=String(amplitude*100);time=0;running=false;ui();});
document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode!;time=0;running=false;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));ui();}));$('#apply').addEventListener('click',()=>{time=0;running=mode==='oscillation';ui();});$('#pause').addEventListener('click',()=>{running=!running;ui();});$('#chartType').addEventListener('change',ui);$('#resetTop').addEventListener('click',()=>location.reload());
function frame(now:number){const dt=Math.min((now-last)/1000,.05);last=now;if(running)time+=dt;draw();ui();requestAnimationFrame(frame);}requestAnimationFrame(frame);
