import './style.css';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

type MaterialKey='rubber'|'wood'|'metal'|'ice';
const MATERIALS:Record<MaterialKey,{label:string;color:number,muS:number,muK:number,mass:number}>={
 rubber:{label:'Karet',color:0xef7167,muS:.8,muK:.6,mass:2}, wood:{label:'Kayu',color:0xc79358,muS:.5,muK:.35,mass:1.5},
 metal:{label:'Logam',color:0x9aa8b2,muS:.3,muK:.2,mass:2}, ice:{label:'Es',color:0x9ddce8,muS:.1,muK:.05,mass:1}
};
const app=document.querySelector<HTMLDivElement>('#app')!;
let state={a:2.2,b:5,g:10,material:'wood' as MaterialKey};
let scene:THREE.Scene,camera:THREE.PerspectiveCamera,renderer:THREE.WebGLRenderer,controls:OrbitControls;
let world:THREE.Group,geometryGroup:THREE.Group,rulerGroup:THREE.Group,triangleGroup:THREE.Group,forceGroup:THREE.Group;
let body:THREE.Mesh,trail:THREE.Line,trailPoints:THREE.Vector3[]=[];
let rampDirection=new THREE.Vector3(),bodyPosition=new THREE.Vector3(),running=false,flat=false,distance=0,speed=0,last=0,elapsed=0,showForces=true;
const rampLength=()=>Math.hypot(state.a,state.b),angle=()=>Math.atan2(state.a,state.b),mat=()=>MATERIALS[state.material];
const BLOCK_SIZE=.72;
function createMaterial(key:MaterialKey){const cv=document.createElement('canvas');cv.width=128;cv.height=128;const ctx=cv.getContext('2d')!;ctx.fillStyle='#'+MATERIALS[key].color.toString(16).padStart(6,'0');ctx.fillRect(0,0,128,128);if(key==='wood'){ctx.strokeStyle='rgba(72,35,14,.48)';ctx.lineWidth=5;for(let x=-140;x<180;x+=19){ctx.beginPath();ctx.moveTo(x,0);ctx.bezierCurveTo(x+35,30,x-26,84,x+20,128);ctx.stroke()}}else if(key==='rubber'){ctx.fillStyle='rgba(255,255,255,.16)';for(let y=8;y<128;y+=20)ctx.fillRect(0,y,128,4);ctx.strokeStyle='rgba(70,20,25,.35)';ctx.lineWidth=3;ctx.strokeRect(5,5,118,118)}else if(key==='metal'){const grad=ctx.createLinearGradient(0,0,128,128);grad.addColorStop(0,'rgba(255,255,255,.55)');grad.addColorStop(.45,'rgba(255,255,255,0)');grad.addColorStop(.55,'rgba(0,0,0,.3)');grad.addColorStop(1,'rgba(255,255,255,.25)');ctx.fillStyle=grad;ctx.fillRect(0,0,128,128);ctx.strokeStyle='rgba(30,45,55,.5)';ctx.lineWidth=3;ctx.strokeRect(4,4,120,120)}else{ctx.fillStyle='rgba(255,255,255,.34)';ctx.beginPath();ctx.moveTo(0,24);ctx.lineTo(128,0);ctx.lineTo(128,20);ctx.lineTo(0,44);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,.42)';ctx.lineWidth=3;ctx.strokeRect(4,4,120,120)}const tex=new THREE.CanvasTexture(cv);tex.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshStandardMaterial({color:0xffffff,map:tex,roughness:key==='metal'?.22:.5,metalness:key==='metal'?.75:key==='ice'?.08:.05})}
const fmt=(n:number,d=2)=>n.toFixed(d).replace('.',',');
function page(){app.innerHTML=`<div class="shell"><header><div class="brand"><span class="brand-mark">↗</span><div><b>Physics Lab</b><small>Praktikum Virtual · Gaya Gesek</small></div></div><div class="status"><i></i> EKSPERIMEN <button id="reset" class="ghost">Reset</button></div></header><main><section class="workspace"><aside class="panel controls"><div class="head"><span>01</span><h2>Pengaturan bidang</h2></div><label>Tinggi <output id="aOut">2,20</output> m<input id="a" type="range" min=".2" max="4" step=".05" value="2.2"></label><label>Alas <output id="bOut">5,00</output> m<input id="b" type="range" min="2" max="10" step=".1" value="5"></label><label>Gravitasi <output id="gOut">10</output> m/s²<input id="g" type="range" min="1" max="20" step=".5" value="10"></label><label>Jenis benda<select id="material"><option value="rubber">Karet</option><option value="wood" selected>Kayu</option><option value="metal">Logam</option><option value="ice">Es</option></select></label><div class="geometry"><div><span>a · tinggi AC</span><b id="aRead">2,20 m</b></div><div><span>b · alas AB</span><b id="bRead">5,00 m</b></div><div><span>c · lintasan BC</span><b id="cRead">5,46 m</b></div><div><span>θ · sudut B</span><b id="angleRead">23,75°</b></div></div><button id="release" class="primary">▶ Lepaskan benda</button><button id="tilt" class="outline">＋ Naikkan sudut +1°</button><button id="forces" class="outline active">Arah gaya 2D: tampil</button><div class="statebox"><span>Status benda</span><strong id="motion">SIAP</strong><small id="motionNote">Naikkan sudut perlahan atau lepaskan benda.</small></div></aside><section class="panel stage"><div class="stagebar"><span class="tag">3D VIEWPORT · 16:9</span><div class="views"><button id="side" class="active">Samping</button><button id="top">Atas</button></div></div><div id="viewport" class="viewport"><div class="overlay"><span id="time">t = 0,00 s</span><span id="phase">SIAP</span></div><canvas id="force2d" class="force2d"></canvas><div class="axis x">jarak (m)</div><div class="axis y">tinggi (m)</div></div><div class="legend"><span><i class="ball"></i>Benda</span><span><i class="trail"></i>Jejak gerak</span><span><i class="ramp"></i>Bidang miring + datar</span><span><i class="force"></i>Arah gaya</span></div></section></section><section class="formula panel"><div><span>GEOMETRI SEGITIGA ABC</span><b>c² = a² + b²</b></div><div><span>TRIGONOMETRI</span><b>sin θ = a/c · cos θ = b/c · tan θ = a/b</b></div><div><span>GESER STATIS</span><b>μ<sub>s</sub> = tan θ<sub>kritis</sub></b></div></section></main><footer><span>PHYSICS LAB / SUKA OLIMPIADE FISIKA</span><span>Benda berlanjut ke bidang datar</span></footer></div>`}
function canvasLabel(text:string,pos:THREE.Vector3,size=1,target:THREE.Group=rulerGroup){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=64;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#d5eded';ctx.font='bold 30px monospace';ctx.textAlign='center';ctx.fillText(text,128,40);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(canvas),transparent:true,depthTest:false}));sprite.scale.set(size,size*.25,1);sprite.position.copy(pos);target.add(sprite)}
function line(points:THREE.Vector3[],color=0x91adb0,dashed=false){const m=dashed?new THREE.LineDashedMaterial({color,dashSize:.12,gapSize:.08}):new THREE.LineBasicMaterial({color});const l=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),m);if(dashed){l.computeLineDistances()}return l}
function clearGroup(g:THREE.Group){while(g.children.length){const x=g.children.pop()!;x.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line||o instanceof THREE.Sprite){o.geometry?.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material?.dispose()}})}}
function pointAt(u:number){const th=angle(),cl=rampLength();const planeOffset=.11+BLOCK_SIZE/2;return u<=cl?new THREE.Vector3(u*Math.cos(th)+Math.sin(th)*planeOffset,state.a-u*Math.sin(th)+Math.cos(th)*planeOffset,0):new THREE.Vector3(state.b+(u-cl),.375,0)}
function buildTriangle(){clearGroup(triangleGroup);const A=new THREE.Vector3(0,.03,-1.18),B=new THREE.Vector3(state.b,.03,-1.18),C=new THREE.Vector3(0,state.a,-1.18);triangleGroup.add(line([A,B],0x54d0df));triangleGroup.add(line([A,C],0xff9f68,true));triangleGroup.add(line([C,B],0x9df5c2));canvasLabel('A',A.clone().add(new THREE.Vector3(-.2,.15,0)),.65,triangleGroup);canvasLabel('B',B.clone().add(new THREE.Vector3(.2,.15,0)),.65,triangleGroup);canvasLabel('C',C.clone().add(new THREE.Vector3(-.2,.15,0)),.65,triangleGroup);canvasLabel(`a = ${fmt(state.a)} m`,A.clone().lerp(C,.5).add(new THREE.Vector3(-.45,0,0)),.82,triangleGroup);canvasLabel(`b = ${fmt(state.b)} m`,A.clone().lerp(B,.5).add(new THREE.Vector3(0,-.2,0)),.82,triangleGroup);canvasLabel(`c = ${fmt(rampLength())} m`,C.clone().lerp(B,.5).add(new THREE.Vector3(.05,.22,0)),.82,triangleGroup)}
function buildRuler(){clearGroup(rulerGroup);const th=angle(),cl=rampLength(),p=(u:number)=>new THREE.Vector3(u*Math.cos(th),.08+u*Math.sin(th),-.68);for(const u of [0,cl/2,cl]){rulerGroup.add(line([p(u),p(u).add(new THREE.Vector3(-.14*Math.sin(th),.14*Math.cos(th),0))]));canvasLabel(`${fmt(u)} m`,p(u).add(new THREE.Vector3(0,.18,0)),.7)}for(let x=0;x<=state.b+9;x+=1){rulerGroup.add(line([new THREE.Vector3(state.b+x,.08,-.7),new THREE.Vector3(state.b+x,.08,-1.02)],0x91adb0));if(x%2===0)canvasLabel(`${x} m`,new THREE.Vector3(state.b+x,.14,-1.3),.68)}}
function updateForces(){if(!body)return;clearGroup(forceGroup);const th=angle(),p=body.position.clone().add(new THREE.Vector3(0,.5,0));const gravity=new THREE.Vector3(0,-1,0),normal=new THREE.Vector3(Math.sin(th),Math.cos(th),0),friction=new THREE.Vector3(-Math.cos(th),Math.sin(th),0);forceGroup.add(new THREE.ArrowHelper(gravity,p,.9,0xff6b6b,.16,.09));forceGroup.add(new THREE.ArrowHelper(normal,p,.75,0x54d0df,.14,.08));forceGroup.add(new THREE.ArrowHelper(friction,p,.68,0xffc857,.14,.08))}
function buildGeometry(){clearGroup(geometryGroup);const th=angle(),cl=rampLength();const ramp=new THREE.Mesh(new THREE.BoxGeometry(cl,.22,2.4),new THREE.MeshStandardMaterial({color:0x3a4546,roughness:.7}));ramp.rotation.z=-th;ramp.position.set(state.b/2,state.a/2,0);ramp.receiveShadow=true;geometryGroup.add(ramp);const floor=new THREE.Mesh(new THREE.BoxGeometry(state.b+11,.25,3.6),new THREE.MeshStandardMaterial({color:0x242d31,roughness:.82}));floor.position.set(state.b+(state.b+11)/2,-.14,0);floor.receiveShadow=true;geometryGroup.add(floor);buildTriangle();buildRuler();updateForces();fit()}
function setMaterial(){const old=body.material as THREE.MeshStandardMaterial;const next=createMaterial(state.material);body.material=next;old.map?.dispose();old.dispose()}
function buildScene(){const el=document.querySelector<HTMLDivElement>('#viewport')!;scene=new THREE.Scene();scene.background=new THREE.Color(0x0c1013);camera=new THREE.PerspectiveCamera(35,el.clientWidth/el.clientHeight,.1,500);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(2,devicePixelRatio));renderer.setSize(el.clientWidth,el.clientHeight);renderer.shadowMap.enabled=true;el.appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=1.48;scene.add(new THREE.HemisphereLight(0xdceeff,0x15110d,2));const light=new THREE.DirectionalLight(0xffffff,2.5);light.position.set(5,14,8);light.castShadow=true;scene.add(light);world=new THREE.Group();geometryGroup=new THREE.Group();rulerGroup=new THREE.Group();triangleGroup=new THREE.Group();forceGroup=new THREE.Group();world.add(geometryGroup,rulerGroup,triangleGroup,forceGroup);scene.add(world);body=new THREE.Mesh(new THREE.BoxGeometry(BLOCK_SIZE,BLOCK_SIZE,BLOCK_SIZE),createMaterial(state.material));body.castShadow=true;scene.add(body);trail=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xffa06d,transparent:true,opacity:.9}));scene.add(trail);buildGeometry();body.position.copy(pointAt(0));updateForces();resize();animate(0)}
function fit(top=false){const span=state.b+10,h=state.a+3;camera.position.set(span*.52,top?span+4:h*.42+span*.34,top?.01:span);controls.target.set(state.b*.55,h*.28,0);controls.update()}
function resize(){const el=document.querySelector<HTMLDivElement>('#viewport')!;camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight);const c=document.querySelector<HTMLCanvasElement>('#force2d')!;c.width=el.clientWidth*devicePixelRatio;c.height=el.clientHeight*devicePixelRatio;c.style.width='100%';c.style.height='100%';draw2D()}
function resetObject(){running=false;flat=false;distance=0;speed=0;elapsed=0;trailPoints=[];trail.geometry.dispose();trail.geometry=new THREE.BufferGeometry();body.rotation.z=-angle();body.position.copy(pointAt(0));updateForces();setStatus('SIAP','Naikkan sudut perlahan atau lepaskan benda.')}
function setStatus(status:string,note:string){document.querySelector('#motion')!.textContent=status;document.querySelector('#motionNote')!.textContent=note;document.querySelector('#phase')!.textContent=status}
function addTrail(){trailPoints.push(body.position.clone());if(trailPoints.length>260)trailPoints.shift();trail.geometry.dispose();trail.geometry=new THREE.BufferGeometry().setFromPoints(trailPoints)}
function drawArrow(ctx:CanvasRenderingContext2D,x:number,y:number,dx:number,dy:number,color:string,labelText:string){ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+dx,y+dy);ctx.stroke();const a=Math.atan2(dy,dx);ctx.beginPath();ctx.moveTo(x+dx,y+dy);ctx.lineTo(x+dx-8*Math.cos(a-.45),y+dy-8*Math.sin(a-.45));ctx.lineTo(x+dx-8*Math.cos(a+.45),y+dy-8*Math.sin(a+.45));ctx.closePath();ctx.fill();ctx.font='11px monospace';ctx.fillText(labelText,x+dx+5,y+dy+4)}
function draw2D(){const canvas=document.querySelector<HTMLCanvasElement>('#force2d');if(!canvas)return;const ctx=canvas.getContext('2d')!,w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);if(!showForces)return;const pad=18*devicePixelRatio,scale=Math.min((w-2*pad)/(state.b+8),(h-2*pad)/(state.a+2.5));const ox=pad,oy=h-pad;const X=(x:number)=>ox+x*scale,Y=(y:number)=>oy-y*scale;ctx.fillStyle='rgba(8,14,17,.86)';ctx.fillRect(10*devicePixelRatio,10*devicePixelRatio,270*devicePixelRatio,125*devicePixelRatio);ctx.fillStyle='#dceaea';ctx.font=`${11*devicePixelRatio}px monospace`;ctx.fillText('ARAH GAYA · TAMPAK SAMPING',24*devicePixelRatio,32*devicePixelRatio);ctx.strokeStyle='#54d0df';ctx.lineWidth=2*devicePixelRatio;ctx.beginPath();ctx.moveTo(X(0),Y(0));ctx.lineTo(X(state.b),Y(0));ctx.stroke();ctx.strokeStyle='#9df5c2';ctx.beginPath();ctx.moveTo(X(0),Y(state.a));ctx.lineTo(X(state.b),Y(0));ctx.stroke();ctx.strokeStyle='#ff9f68';ctx.setLineDash([5*devicePixelRatio,4*devicePixelRatio]);ctx.beginPath();ctx.moveTo(X(0),Y(0));ctx.lineTo(X(0),Y(state.a));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#d5eded';ctx.font=`${11*devicePixelRatio}px monospace`;ctx.fillText('A',X(0)-12,Y(0)+16);ctx.fillText('B',X(state.b)+7,Y(0)+16);ctx.fillText('C',X(0)-12,Y(state.a)-8);ctx.fillText(`a=${fmt(state.a)}m`,X(0)-45,Y(state.a/2));ctx.fillText(`b=${fmt(state.b)}m`,X(state.b/2)-20,Y(0)+30);ctx.fillText(`c=${fmt(rampLength())}m`,X(state.b/2)+8,Y(state.a/2)-8);const th2=angle(),cl2=rampLength();let px:number,py:number;const support=.11+BLOCK_SIZE/2;const scaleSupport=scale;if(flat){px=X(state.b+(distance-cl2));py=Y(.375)}else{const surfaceX=distance*Math.cos(th2),surfaceY=state.a-distance*Math.sin(th2);px=X(surfaceX)+Math.sin(th2)*support*scaleSupport;py=Y(surfaceY)-Math.cos(th2)*support*scaleSupport}const viewAngle=flat?0:th2;const half=BLOCK_SIZE/2*scale;ctx.save();ctx.translate(px,py);ctx.rotate(viewAngle);ctx.fillStyle='#54d0df';ctx.fillRect(-half,-half,half*2,half*2);ctx.strokeStyle='#e8ffff';ctx.lineWidth=1.5*devicePixelRatio;ctx.strokeRect(-half,-half,half*2,half*2);ctx.restore();const tangentX=Math.cos(viewAngle),tangentY=Math.sin(viewAngle);const normalDownX=-Math.sin(viewAngle),normalDownY=Math.cos(viewAngle);const contactX=px+normalDownX*half,contactY=py+normalDownY*half;ctx.strokeStyle='#f4c56b';ctx.lineWidth=3*devicePixelRatio;ctx.beginPath();ctx.moveTo(contactX-tangentX*half,contactY-tangentY*half);ctx.lineTo(contactX+tangentX*half,contactY+tangentY*half);ctx.stroke();const th=angle();drawArrow(ctx,px,py,0,35*devicePixelRatio,'#ff6b6b','mg');drawArrow(ctx,px,py,Math.sin(th)*35*devicePixelRatio,-Math.cos(th)*35*devicePixelRatio,'#54d0df','N');drawArrow(ctx,px,py,-Math.cos(th)*32*devicePixelRatio,Math.sin(th)*32*devicePixelRatio,'#ffc857','f');}
function animate(now:number){requestAnimationFrame(animate);const dt=Math.min(.04,(now-last)/1000||0);last=now;if(running){elapsed+=dt;const th=angle(),cl=rampLength(),m=mat();if(!flat){if(speed===0&&Math.sin(th)<=m.muS*Math.cos(th)){running=false;setStatus('TETAP DIAM','Sudut belum melewati sudut kritis. Naikkan sudut.')}else{speed+=state.g*(Math.sin(th)-m.muK*Math.cos(th))*dt;distance+=speed*dt;if(distance>=cl){distance=cl;flat=true;setStatus('BIDANG DATAR','Benda melanjutkan gerak pada bidang datar.')}}}else{speed=Math.max(0,speed-state.g*m.muK*dt);distance+=speed*dt;if(speed<=.01){running=false;setStatus('BERHENTI','Benda berhenti setelah gaya gesek menghabiskan energi kinetik.')}}body.position.copy(pointAt(distance));body.rotation.z=flat?0:-th;addTrail();updateForces();draw2D()}document.querySelector('#time')!.textContent='t = '+fmt(elapsed)+' s';controls.update();renderer.render(scene,camera)}
function bind(){['a','b','g'].forEach(id=>document.querySelector<HTMLInputElement>('#'+id)!.addEventListener('input',e=>{(state as any)[id]=Number((e.target as HTMLInputElement).value);resetObject();buildGeometry();updateUI()}));document.querySelector('#material')!.addEventListener('change',e=>{state.material=(e.target as HTMLSelectElement).value as MaterialKey;setMaterial();resetObject()});document.querySelector('#release')!.addEventListener('click',()=>{resetObject();running=true;setStatus('BIDANG MIRING','Benda bergerak menuju bidang datar.');draw2D()});document.querySelector('#tilt')!.addEventListener('click',()=>{const d=Math.min(75,THREE.MathUtils.radToDeg(angle())+1);state.a=Math.tan(THREE.MathUtils.degToRad(d))*state.b;(document.querySelector('#a') as HTMLInputElement).value=String(state.a);resetObject();buildGeometry();updateUI();setStatus('SUDUT DIUBAH','Sudut bidang dan segitiga ABC sudah diperbarui.')});document.querySelector('#forces')!.addEventListener('click',e=>{showForces=!showForces;(e.currentTarget as HTMLButtonElement).textContent=`Arah gaya 2D: ${showForces?'tampil':'sembunyi'}`;draw2D()});document.querySelector('#reset')!.addEventListener('click',()=>{state={a:2.2,b:5,g:10,material:'wood'};(['a','b','g'] as const).forEach(id=>(document.querySelector('#'+id) as HTMLInputElement).value=String((state as any)[id]));(document.querySelector('#material') as HTMLSelectElement).value='wood';setMaterial();resetObject();buildGeometry();updateUI()});document.querySelector('#side')!.addEventListener('click',()=>fit());document.querySelector('#top')!.addEventListener('click',()=>fit(true))}
function updateUI(){document.querySelector('#aOut')!.textContent=fmt(state.a);document.querySelector('#bOut')!.textContent=fmt(state.b);document.querySelector('#gOut')!.textContent=fmt(state.g,1);document.querySelector('#aRead')!.textContent=fmt(state.a)+' m';document.querySelector('#bRead')!.textContent=fmt(state.b)+' m';document.querySelector('#cRead')!.textContent=fmt(rampLength())+' m';document.querySelector('#angleRead')!.textContent=fmt(THREE.MathUtils.radToDeg(angle()))+'°';draw2D()}
page();buildScene();bind();updateUI();
