import './style.css';
import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
type Kind='venturi'|'pendulum'|'wave'|'heat'|'induction';
const specs:any={venturi:['Fluida Venturi & Bernoulli',['Luas penampang','Debit aliran','Ketinggian'],['cm²','L/s','m'],[2,4,0]],pendulum:['Bandul sederhana',['Panjang tali','Sudut awal','Massa'],['m','°','kg'],[2,25,1]],wave:['Gelombang pada tali',['Amplitudo','Frekuensi','Tegangan'],['cm','Hz','N'],[.4,1,25]],heat:['Kalor & energi',['Massa air','Suhu awal','Daya'],['kg','°C','W'],[1,25,500]],induction:['Induksi elektromagnetik',['Jumlah lilitan','Kecepatan magnet','Kuat magnet'],['lilitan','m/s','T'],[80,1,.5]]};
let kind:Kind='induction',vals=[...specs[kind][3]],running=true,t=0,last=performance.now();const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;const f=(v:number)=>v.toFixed(2).replace('.',',');
$('body');
function html(){return `<div class="shell"><header><div class="brand"><span class="mark">✦</span><div><b>Physics Lab</b><small>Lima simulasi praktikum 3D</small></div></div><button id="reset" class="ghost">Reset</button></header><nav class="tabs">${(Object.keys(specs) as Kind[]).map((k,i)=>`<button data-kind="${k}" class="${k===kind?'active':''}">0${i+1} · ${specs[k][0]}</button>`).join('')}</nav><main class="layout"><aside class="left"><section class="panel controls"><div class="eyebrow">VARIABEL PERCOBAAN</div><div class="actions"><button id="pause" class="secondary">Jeda</button><button id="apply" class="primary">Terapkan</button></div><div id="fields"></div><div class="toggles"><label><span>Jejak / partikel</span><input id="trail" type="checkbox" checked></label><label><span>Vektor / medan</span><input id="vectors" type="checkbox" checked></label></div></section><section class="panel analysis"><div class="eyebrow">ANALISIS LANGSUNG</div><div id="stats" class="stats"></div><div id="formula" class="formula"></div></section></aside><section class="panel stage"><div class="stagebar"><span class="tag">3D VIEWPORT · 16:9 · WEBGL</span><span id="status">BERJALAN</span></div><div id="viewport" class="viewport"><div class="hud"><span id="hudL"></span><span id="hudR"></span></div></div><div id="legend" class="legend"></div><div class="question"><b>Pertanyaan eksperimen</b><p id="question"></p></div></section></main><footer><span>SUKA OLIMPIADE FISIKA</span><span>Three.js · Eksperimen interaktif</span></footer></div>`}
$('body').innerHTML=html();const viewport=$<HTMLElement>('#viewport'),scene=new THREE.Scene();scene.background=new THREE.Color(0x101a16);const cam=new THREE.PerspectiveCamera(45,1,.1,100);cam.position.set(6,5,7);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));viewport.appendChild(renderer.domElement);const orbit=new OrbitControls(cam,renderer.domElement);orbit.enableDamping=true;orbit.target.set(0,0,0);scene.add(new THREE.HemisphereLight(0xeafff4,0x26382d,2));const lamp=new THREE.DirectionalLight(0xffffff,3);lamp.position.set(4,8,5);scene.add(lamp);const root=new THREE.Group();scene.add(root);const material=(c:number)=>new THREE.MeshStandardMaterial({color:c,roughness:.35,metalness:.15});function clear(){root.clear()}
function build(){clear();const s=specs[kind];$('#fields').innerHTML=s[1].map((x:string,i:number)=>`<label>${x}<output id="o${i}">${f(vals[i])} ${s[2][i]}</output><input data-i="${i}" type="range" min="${i===0?.1:1}" max="${i===0?4:i===1?8:50}" step="${i===0?.1:1}" value="${vals[i]}"></label>`).join('');$('#question').textContent=kind==='venturi'?'Pada bagian sempit, bagaimana perubahan kecepatan dan tekanan?':kind==='pendulum'?'Apakah massa mengubah periode bandul?':kind==='wave'?'Bagaimana perubahan panjang gelombang saat frekuensi dinaikkan?':kind==='heat'?'Apa dampak penggandaan daya pada laju kenaikan suhu?':'Kapan GGL induksi paling besar?';$('#formula').innerHTML='<b>'+({venturi:'A₁v₁ = A₂v₂',pendulum:'T = 2π√(L/g)',wave:'v = fλ',heat:'Q = mcΔT',induction:'ε = −N ΔΦ/Δt'} as any)[kind]+'</b>';let text='';
if(kind==='venturi'){for(let i=0;i<14;i++){const q=new THREE.Mesh(new THREE.SphereGeometry(.07,8,8),material(0x65d8e3));q.userData.i=i;root.add(q)}const pipe=new THREE.Mesh(new THREE.BoxGeometry(6,.7,1.2),material(0x2e7582));pipe.position.y=-.2;root.add(pipe);text='Pipa Venturi · Partikel fluida · Penampang sempit'}
if(kind==='pendulum'){const pvt=new THREE.Mesh(new THREE.SphereGeometry(.12,16,12),material(0xbdd44a));pvt.position.y=2.5;root.add(pvt);const rod=new THREE.Mesh(new THREE.CylinderGeometry(.03,.03,2.4,12),material(0xd0d8d2));rod.userData.rod=true;root.add(rod);const bob=new THREE.Mesh(new THREE.SphereGeometry(.3,24,16),material(0x65d8e3));bob.userData.bob=true;root.add(bob);text='Bandul · Posisi setimbang · Sudut awal'}
if(kind==='wave'){for(let i=0;i<45;i++){const q=new THREE.Mesh(new THREE.SphereGeometry(.08,8,8),material(0x65d8e3));q.userData.i=i;root.add(q)}text='Tali · Partikel gelombang · Arah rambat'}
if(kind==='heat'){const box=new THREE.Mesh(new THREE.BoxGeometry(4,2.5,2.3),new THREE.MeshStandardMaterial({color:0x4f91a0,transparent:true,opacity:.18}));box.position.y=.8;root.add(box);for(let i=0;i<28;i++){const q=new THREE.Mesh(new THREE.SphereGeometry(.08,8,8),material(0xf39b68));q.userData.i=i;q.position.set((i%7-3)*.45,(Math.floor(i/7)%4)*.35,(i%4-1.5)*.4);root.add(q)}text='Wadah air · Partikel termal · Pemanas'}
if(kind==='induction'){const coil=new THREE.Mesh(new THREE.TorusGeometry(1.1,.08,12,64),material(0xf39b68));coil.rotation.x=Math.PI/2;root.add(coil);const magnet=new THREE.Mesh(new THREE.CylinderGeometry(.25,.25,.9,24),material(0xbcd0d2));magnet.rotation.z=Math.PI/2;magnet.userData.magnet=true;root.add(magnet);text='Kumparan · Magnet batang · Garis fluks'}$('#legend').textContent=text;document.querySelectorAll<HTMLInputElement>('[data-i]').forEach(i=>i.addEventListener('input',()=>{vals[Number(i.dataset.i)]=Number(i.value);$('#o'+i.dataset.i).textContent=f(vals[Number(i.dataset.i)])+' '+s[2][Number(i.dataset.i)];build()}));document.querySelectorAll<HTMLButtonElement>('[data-kind]').forEach(b=>b.classList.toggle('active',b.dataset.kind===kind));ui()}
function ui(){const a=vals[0],b=vals[1],c=vals[2];let rows:any[]=[];if(kind==='venturi')rows=[['v₁',f(b/a*.4)+' m/s'],['v₂',f(b/a*.8)+' m/s'],['ΔP',f((b/a)**2)+' unit']];if(kind==='pendulum'){const T=2*Math.PI*Math.sqrt(a/9.81);rows=[['Periode',f(T)+' s'],['Frekuensi',f(1/T)+' Hz'],['Simpangan',f(a*Math.sin(c*Math.PI/180)*100)+' cm']]}if(kind==='wave'){const v=Math.sqrt(c);rows=[['Cepat rambat',f(v)+' m/s'],['Panjang λ',f(v/b)+' m'],['Periode',f(1/b)+' s']]}if(kind==='heat'){rows=[['Suhu model',f(25+c*t/(a*4180))+' °C'],['Laju ΔT',f(c/(a*4180)*60)+' °C/menit'],['Energi',f(c*t)+' J']]}if(kind==='induction')rows=[['GGL relatif',f(a*b*c*.8)+' V'],['Fluks',f(b*c)+' Wb'],['Status',b>0?'bergerak':'diam']];$('#stats').innerHTML=rows.map(r=>`<div><span>${r[0]}</span><b>${r[1].split(' ')[0]}</b><small>${r[1].split(' ').slice(1).join(' ')}</small></div>`).join('');$('#hudL').textContent=specs[kind][0];$('#hudR').textContent=kind==='heat'?'t = '+f(t)+' s':'Eksperimen aktif';$('#status').textContent=running?'BERJALAN':'DIJEDA'}
function animate(){const now=performance.now(),dt=Math.min(.05,(now-last)/1000);last=now;if(running)t+=dt;const a=vals[0],b=vals[1],c=vals[2];if(kind==='venturi')root.children.forEach((x:any)=>{if(x.userData.i!==undefined)x.position.set(((x.userData.i+t*b*.8)%14)-7,0,((x.userData.i*1.7)%3-1)*.25)});if(kind==='pendulum'){const ang=c*Math.PI/180*Math.cos(Math.sqrt(9.81/a)*t),rod=root.children.find((x:any)=>x.userData.rod),bob=root.children.find((x:any)=>x.userData.bob);if(rod&&bob){rod.position.set(Math.sin(ang)*a*.6,2.5-Math.cos(ang)*a*.6,0);rod.rotation.z=ang;bob.position.set(Math.sin(ang)*a*1.2,2.5-Math.cos(ang)*a*1.2,0)}}if(kind==='wave')root.children.forEach((x:any)=>{if(x.userData.i!==undefined){const xx=-3+x.userData.i*6/44;x.position.set(xx,-.2+Math.sin(x.userData.i/44*Math.PI*5-b*t*3)*a,0)}});if(kind==='heat')root.children.forEach((x:any)=>{if(x.userData.i!==undefined){x.position.x+=Math.sin(t*2+x.userData.i)*dt*.08;x.position.z+=Math.cos(t*1.7+x.userData.i)*dt*.08}});if(kind==='induction'){const m=root.children.find((x:any)=>x.userData.magnet);if(m)m.position.x=Math.sin(t*b)*1.8}orbit.update();renderer.render(scene,cam);ui();requestAnimationFrame(animate)}
document.querySelectorAll<HTMLButtonElement>('[data-kind]').forEach(b=>b.addEventListener('click',()=>{kind=b.dataset.kind as Kind;vals=[...specs[kind][3]];t=0;build()}));$('#pause').addEventListener('click',e=>{running=!running;(e.currentTarget as HTMLButtonElement).textContent=running?'Jeda':'Lanjutkan';ui()});$('#apply').addEventListener('click',()=>{t=0;running=true;$('#pause').textContent='Jeda';build()});$('#reset').addEventListener('click',()=>location.reload());new ResizeObserver(()=>{const r=viewport.getBoundingClientRect();renderer.setSize(r.width,r.height,false);cam.aspect=r.width/Math.max(r.height,1);cam.updateProjectionMatrix()}).observe(viewport);build();const r=viewport.getBoundingClientRect();renderer.setSize(r.width,r.height,false);animate();
