import './style.css';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

type Point={angle:number;v0:number;flight:number;height:number;range:number};
const root=document.querySelector<HTMLDivElement>('#app')!;
let state={v0:20,angle:45,g:10,height:0,timeScale:1}; let points:Point[]=[]; let running=false,simTime=0,last=0;
let scene:THREE.Scene,camera:THREE.PerspectiveCamera,renderer:THREE.WebGLRenderer,controls:OrbitControls,ball:THREE.Mesh,trajectory:THREE.Line,trailLine:THREE.Line,marker:THREE.Mesh,rulerGroup:THREE.Group,floorMesh:THREE.Mesh;
let trailPoints:THREE.Vector3[]=[]; let bounceActive=false,bounceY=0,bounceVy=0,bounceX=0,bounceVx=0,bounceCount=0; const ballRadius=.34;
function calc(v0:number,deg:number,g:number,h=0){const th=THREE.MathUtils.degToRad(deg),vx=v0*Math.cos(th),vy=v0*Math.sin(th),flight=(vy+Math.sqrt(vy*vy+2*g*h))/g;return{vx,vy,flight,range:vx*flight,height:h+vy*vy/(2*g)}}
function fmt(n:number,d=2){return n.toFixed(d).replace('.',',')}
function page(){root.innerHTML=`<div class="app-shell"><header><div class="brand"><span class="brand-mark">↗</span><div><b>Physics Lab</b><small>Praktikum Virtual</small></div></div><div class="header-status"><span class="live"></span> SIMULASI AKTIF <button id="resetAll" class="ghost">Reset</button></div></header><main><section class="workspace"><aside class="controls panel"><div class="panel-head"><span>01</span><h2>Parameter eksperimen</h2></div><label>Kecepatan awal <output id="v0Out">20</output> <small>m/s</small><input id="v0" type="range" min="5" max="35" step="1" value="20"></label><label>Sudut peluncuran <output id="angleOut">45</output> <small>°</small><input id="angle" type="range" min="5" max="85" step="1" value="45"></label><label>Gravitasi <output id="gOut">10</output> <small>m/s²</small><input id="g" type="range" min="1" max="20" step="0.5" value="10"></label><div class="button-row"><button id="run" class="primary">▶ Mulai eksperimen</button><button id="pause" class="secondary">Ⅱ Jeda</button></div><div class="readout"><div><span>Jarak horizontal</span><b id="rangeOut">40,00 m</b></div><div><span>Tinggi maksimum</span><b id="heightOut">10,00 m</b></div><div><span>Waktu terbang</span><b id="flightOut">2,83 s</b></div></div><div class="hint"><b>Variabel eksperimen</b><p>Ubah satu variabel, jalankan simulasi, lalu simpan hasilnya ke tabel. Jarak dan waktu dihitung sampai sentuhan lantai pertama; pantulan adalah gerak lanjutan.</p></div></aside><div class="stage panel"><div class="stage-top"><div><span class="tag">3D VIEWPORT · 16:9</span></div><div class="stage-actions"><button id="viewSide" class="active">Samping</button><button id="viewTop">Atas</button></div></div><div id="viewport" class="viewport"><div class="axis-label x-label">x (m)</div><div class="axis-label y-label">y (m)</div><div class="stage-overlay"><span id="simTime">t = 0,00 s</span><span id="simState">READY</span></div></div><div class="legend"><span><i class="dot ball-dot"></i>Proyektil</span><span><i class="line-dash"></i>Lintasan</span><span><i class="arrow-dot"></i>Jejak gerak</span></div></div></section></main><footer><span>PHYSICS LAB / SUKA OLIMPIADE FISIKA</span><span>Eksperimen tanpa hambatan udara · g dapat diubah</span></footer></div>`}
function setup3D(){const el=document.querySelector<HTMLDivElement>('#viewport')!;scene=new THREE.Scene();scene.background=new THREE.Color(0x0d1115);camera=new THREE.PerspectiveCamera(38,el.clientWidth/el.clientHeight,.1,400);camera.position.set(20,18,34);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(2,devicePixelRatio));renderer.setSize(el.clientWidth,el.clientHeight);renderer.shadowMap.enabled=true;el.appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,4,0);controls.maxPolarAngle=Math.PI*.48;scene.add(new THREE.HemisphereLight(0xddeeff,0x15110d,2));const light=new THREE.DirectionalLight(0xffffff,2.4);light.position.set(-8,18,10);light.castShadow=true;scene.add(light);const floor=new THREE.Mesh(new THREE.BoxGeometry(160,.25,7),new THREE.MeshStandardMaterial({color:0x20272a,roughness:.82}));floor.position.y=-.13;floor.receiveShadow=true;floorMesh=floor;scene.add(floor);const grid=new THREE.GridHelper(160,80,0x344247,0x202a2d);grid.position.y=.02;grid.scale.z=.7;scene.add(grid);scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-5,.05,0),new THREE.Vector3(155,.05,0)]),new THREE.LineBasicMaterial({color:0x6bcbd8})));ball=new THREE.Mesh(new THREE.SphereGeometry(ballRadius,28,18),new THREE.MeshStandardMaterial({color:0x54d0df,emissive:0x0d4b56,emissiveIntensity:.7,roughness:.28,metalness:.2}));ball.castShadow=true;scene.add(ball);ball.position.y=ballRadius;marker=new THREE.Mesh(new THREE.RingGeometry(ballRadius*1.03,ballRadius*1.22,32),new THREE.MeshBasicMaterial({color:0x54d0df,transparent:true,opacity:.7,side:THREE.DoubleSide}));marker.rotation.x=-Math.PI/2;marker.position.y=.03;scene.add(marker);rulerGroup=new THREE.Group();scene.add(rulerGroup);buildRuler();trailLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xff9f68,transparent:true,opacity:.9}));scene.add(trailLine);buildTrajectory();fitCamera();resize();window.addEventListener('resize',resize);animate(0)}
function buildRuler(){
 const c=calc(state.v0,state.angle,state.g),extent=Math.max(30,c.range*2.3),step=Math.pow(10,Math.floor(Math.log10(extent/12))),spacing=extent/step>24?step*5:extent/step>14?step*2:step;
 while(rulerGroup.children.length){const child=rulerGroup.children[0];rulerGroup.remove(child);if(child instanceof THREE.Line){child.geometry.dispose();(child.material as THREE.Material).dispose()}if(child instanceof THREE.Sprite){child.material.map?.dispose();child.material.dispose()}}
 floorMesh.scale.x=extent/160;floorMesh.position.x=extent/2-2;
 for(let x=0;x<=extent;x+=spacing){const tick=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(x,.08,-.8),new THREE.Vector3(x,.08,-1.6)]),new THREE.LineBasicMaterial({color:0x9cbdc1}));rulerGroup.add(tick);
 const canvas=document.createElement('canvas');canvas.width=192;canvas.height=64;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#d5eded';ctx.font='bold 32px monospace';ctx.textAlign='center';ctx.fillText(`${Number(x.toFixed(1))} m`,96,40);
 const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(canvas),transparent:true,depthTest:false}));const size=Math.max(2,extent/24);sprite.scale.set(size,size/3,1);sprite.position.set(x,.12,-2.3);rulerGroup.add(sprite)}
}
function fitCamera(top=false){const c=calc(state.v0,state.angle,state.g),width=Math.max(30,c.range*2.3),height=Math.max(10,c.height+3);const center=width/2-2;const distance=Math.max(width/camera.aspect,height*1.65)/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2)))*1.22;camera.far=Math.max(400,distance*6);camera.updateProjectionMatrix();controls.target.set(center,height*.4,0);camera.position.set(center,top?distance+height:height*.4+distance*.16,top?.01:distance);controls.update()}
function resize(){const el=document.querySelector<HTMLDivElement>('#viewport');if(!el||!renderer)return;camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight);fitCamera()}
function buildTrajectory(){if(trajectory){trajectory.geometry.dispose();scene.remove(trajectory)}const c=calc(state.v0,state.angle,state.g,state.height),pts=[];for(let i=0;i<=80;i++){const t=c.flight*i/80;pts.push(new THREE.Vector3(c.vx*t,ballRadius+state.height+c.vy*t-.5*state.g*t*t,0))}trajectory=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x54d0df,transparent:true,opacity:.65}));scene.add(trajectory)}
function updateReadouts(){const c=calc(state.v0,state.angle,state.g,state.height);document.querySelector('#v0Out')!.textContent=String(state.v0);document.querySelector('#angleOut')!.textContent=String(state.angle);document.querySelector('#gOut')!.textContent=String(state.g);document.querySelector('#rangeOut')!.textContent=fmt(c.range)+' m';document.querySelector('#heightOut')!.textContent=fmt(c.height)+' m';document.querySelector('#flightOut')!.textContent=fmt(c.flight)+' s';buildTrajectory();buildRuler();fitCamera()}
function clearTrail(){trailPoints=[];if(trailLine){trailLine.geometry.dispose();trailLine.geometry=new THREE.BufferGeometry()}}
function updateTrail(x:number,y:number){trailPoints.push(new THREE.Vector3(x,Math.max(ballRadius,y),0));if(trailPoints.length>260)trailPoints.shift();trailLine.geometry.dispose();trailLine.geometry=new THREE.BufferGeometry().setFromPoints(trailPoints)}
function resetMotion(){running=false;simTime=0;bounceActive=false;bounceY=state.height;bounceX=0;bounceCount=0;ball.position.set(0,ballRadius+state.height,0);marker.position.x=0;clearTrail();document.querySelector('#simState')!.textContent='READY'}
function animate(now:number){requestAnimationFrame(animate);const dt=Math.min(.04,(now-last)/1000||0);last=now;if(running){const c=calc(state.v0,state.angle,state.g,state.height);if(!bounceActive){simTime+=dt*state.timeScale;if(simTime>=c.flight){simTime=c.flight;bounceActive=true;bounceX=c.range;bounceY=ballRadius;bounceVy=Math.abs(c.vy)*.72;bounceVx=c.vx*.88;bounceCount=0;document.querySelector('#simState')!.textContent='BOUNCE'}else{ball.position.set(c.vx*simTime,ballRadius+state.height+c.vy*simTime-.5*state.g*simTime*simTime,0);marker.position.x=c.vx*simTime;updateTrail(ball.position.x,ball.position.y)}}if(bounceActive){const step=dt*state.timeScale;bounceVy-=state.g*step;bounceY+=bounceVy*step;bounceX+=bounceVx*step;if(bounceY<=ballRadius){bounceY=ballRadius;bounceVy=Math.abs(bounceVy)*.55;bounceVx*=.78;bounceCount++;if(bounceCount>=4||bounceVy<.8){running=false;document.querySelector('#simState')!.textContent='LANDED'}}ball.position.set(bounceX,bounceY,0);marker.position.x=bounceX;updateTrail(bounceX,bounceY)}}document.querySelector('#simTime')!.textContent='t = '+fmt(simTime)+' s';controls.update();renderer.render(scene,camera)}
function drawAxes(ctx:CanvasRenderingContext2D,w:number,h:number,xLabel:string,yLabel:string){ctx.clearRect(0,0,w,h);ctx.fillStyle='#10161a';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#344247';for(let i=0;i<6;i++){const y=25+i*(h-50)/5;ctx.beginPath();ctx.moveTo(42,y);ctx.lineTo(w-12,y);ctx.stroke()}ctx.strokeStyle='#889ba0';ctx.beginPath();ctx.moveTo(42,12);ctx.lineTo(42,h-28);ctx.lineTo(w-10,h-28);ctx.stroke();ctx.fillStyle='#a8b9bb';ctx.font='11px IBM Plex Mono,monospace';ctx.fillText(xLabel,w-80,h-8);ctx.save();ctx.translate(12,h/2);ctx.rotate(-Math.PI/2);ctx.fillText(yLabel,0,0);ctx.restore()}
function drawGraphs(){const samples=points.length?points:[10,20,30,40,45,50,60,70,80].map(angle=>({angle,v0:state.v0,flight:0,height:0,range:calc(state.v0,angle,state.g).range}));drawPlot('graphAngle',samples.map(p=>p.angle),samples.map(p=>p.range),'θ (°)','R (m)',false);drawPlot('graphSin',samples.map(p=>Math.sin(2*p.angle*Math.PI/180)),samples.map(p=>p.range),'sin(2θ)','R (m)',true)}
function drawPlot(id:string,x:Array<number>,y:Array<number>,xlab:string,ylab:string,sort:boolean){const c=document.getElementById(id) as HTMLCanvasElement,ctx=c.getContext('2d')!,w=c.width,h=c.height;drawAxes(ctx,w,h,xlab,ylab);const maxY=y.reduce((a,b)=>Math.max(a,b),1)*1.12,minX=x.reduce((a,b)=>Math.min(a,b),Infinity),maxX=x.reduce((a,b)=>Math.max(a,b),-Infinity),order=sort?x.map((_,i)=>i).sort((a,b)=>x[a]-x[b]):x.map((_,i)=>i);ctx.strokeStyle='#54d0df';ctx.fillStyle='#54d0df';ctx.lineWidth=2;ctx.beginPath();order.forEach((i,j)=>{const px=42+(x[i]-minX)/Math.max(1,maxX-minX)*(w-54),py=h-28-y[i]/maxY*(h-42);j?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke();order.forEach(i=>{const px=42+(x[i]-minX)/Math.max(1,maxX-minX)*(w-54),py=h-28-y[i]/maxY*(h-42);ctx.beginPath();ctx.arc(px,py,3.4,0,Math.PI*2);ctx.fill()})}
function bind(){['v0','angle','g'].forEach(id=>document.querySelector<HTMLInputElement>('#'+id)!.addEventListener('input',e=>{(state as any)[id]=Number((e.target as HTMLInputElement).value);resetMotion();updateReadouts()}));document.querySelector('#run')!.addEventListener('click',()=>{resetMotion();running=true;document.querySelector('#simState')!.textContent='RUNNING';updateTrail(0,state.height)});document.querySelector('#pause')!.addEventListener('click',()=>{running=!running;document.querySelector('#simState')!.textContent=running?'RUNNING':'PAUSED'});document.querySelector('#resetAll')!.addEventListener('click',()=>{state={v0:20,angle:45,g:10,height:0,timeScale:1};points=[];resetMotion();(['v0','angle','g'] as const).forEach(id=>(document.querySelector('#'+id) as HTMLInputElement).value=String((state as any)[id]));updateReadouts()});document.querySelector('#viewSide')!.addEventListener('click',()=>{fitCamera()});document.querySelector('#viewTop')!.addEventListener('click',()=>{fitCamera(true)});}
page();setup3D();bind();updateReadouts();
